### ISSUE TITLE
[ylink]-[Backend-development]-[Resume sample display]【Offer received】

### ISSUE THREAD

**Issue by ylink-lfs** [tx-offer-helper/OurResume#2]

**Comment by tx-offerman** [comment]
甚6， 小程序+django+uwsgi + docker 这个配置， 和我夭折的小程序差不多了。。。。

**Comment by ylink-lfs** [comment]
> 甚6， 小程序+django+uwsgi + docker 这个配置， 和我夭折的小程序差不多了。。。。

docker有美化简历的嫌疑，当时部署没用docker，只是解决一个数据库端口占用问题用到了，面试也跟面试官会解释到

**Comment by tx-offerman** [comment]
> > 甚6， 小程序+django+uwsgi + docker 这个配置， 和我夭折的小程序差不多了。。。。
> 
> docker有美化简历的嫌疑，当时部署没用docker，只是解决一个数据库端口占用问题用到了，面试也跟面试官会解释到

有道理。 这就是套路，自古套路得人心啊。。。。 学到了

**Comment by tx-offerman** [comment]
图片咋上传啊， 我没找到入口。。。。 要自己找图床嘛？

**Comment by ylink-lfs** [comment]
> 图片咋上传啊， 我没找到入口。。。。 要自己找图床嘛？

复制粘贴到编辑器就行啊

**Comment by qinguoyi** [comment]
> 图片咋上传啊， 我没找到入口。。。。 要自己找图床嘛？

是的，我用的新浪图床，直接用github有时候会被墙，刷新不出来
