### ISSUE TITLE
橙子-产品求实习-菜鸡简历求指导

### ISSUE THREAD

**Issue by HosheaJin** [tx-offer-helper/OurResume#5]

**Comment by tx-offerman** [comment]
你感觉你自己有闪光点的项目是啥？ 你自己的特点是啥？ 凭什么面试官会捞你？
这几个问题，先要问自己

**Comment by ylink-lfs** [comment]
获奖经历和兴趣爱好可以砍了，和所求职位无关。慎用熟练，多用了解。

**Comment by ylink-lfs** [comment]
掌握SQL成大学生标配了吗……看到过一个英语专业的学生也这么写，不懂

**Comment by tx-offerman** [comment]
> 掌握SQL成大学生标配了吗……看到过一个英语专业的学生也这么写，不懂

或许吧。。。

**Comment by HosheaJin** [comment]
> 掌握SQL成大学生标配了吗……看到过一个英语专业的学生也这么写，不懂

准备自学的来着。。没什么拿得出手的只能硬顶了

**Comment by HosheaJin** [comment]
> 获奖经历和兴趣爱好可以砍了，和所求职位无关。慎用熟练，多用了解。

好的 谢谢

**Comment by HosheaJin** [comment]
> 你感觉你自己有闪光点的项目是啥？ 你自己的特点是啥？ 凭什么面试官会捞你？
> 这几个问题，先要问自己

现在想想大学期间就应该多参加项目，不该那么水

**Comment by tx-offerman** [comment]
> > 你感觉你自己有闪光点的项目是啥？ 你自己的特点是啥？ 凭什么面试官会捞你？
> > 这几个问题，先要问自己
> 
> 现在想想大学期间就应该多参加项目，不该那么水

简历是可以包装的，项目的目的是证明自己优秀，从这个角度去想，你做啥可以证明自己优秀？ 我做技术，所以我想的，我或多或少参与开源，肯定有点用， 事实证明还是有用的。 你们非技术，虽然方法不可用，但是方法论可以参考
