### ISSUE TITLE
清空

### ISSUE THREAD

**Issue by wenner987** [tx-offer-helper/OurResume#8]
8999
asdd

**Comment by wenner987** [comment]
### 复习经历
    先交代 **阿里、腾讯双offer**
#### 1. 背景
    楼主二本学历本科，在学历比拼上根本没法看。经常被985/211等名校pk下去。技术上略有心得，acm打铁选手，有一定codeing能力。
#### 2. 复习计划
    

- 今年春招是不敢想自己可以拿到大厂offer的。在朋友的哄骗下抱着试一试的心态，投了腾讯、阿里等大厂。然后开始了为期一个月的复习计划。

    

- apue(Unix环境高级编程)看了三遍，从大致看内容，到详细看部分，再到精读，大概花了一周半时间。

    

- 图解TCP(第六章)看了三遍，过程如上。(图解TCP不是最好的网络书籍，但我看了之后觉得很好懂)

    

- IO多路复用模型N篇，网上一搜一大堆。(重要在对比select、pool、epool)

    

- epool源码剖析博文，看了2篇。看懂了epool内容，这部分很简单。

    

- 由于以前接触过一些acm基础知识，对数据结构和算法比较了解。所以数据结构只看了红黑树部分，一篇博文搞定(https://www.jianshu.com/p/e136ec79235c)

- 看一看经典的面经部分，整理玩做好笔记。

- LeetCode 再来个200题

**Comment by wenner987** [comment]
## 菜鸡二本的春招总结

2019年4月28日，春招告一段落了。

2月12日春招开始之前，超提前批面了世纪鲲鹏。并且拿到了offer，并且由于疫情原因无法完成入职。所以一直在推迟，才有后面的故事。

3月6日投递第一份简历到腾讯，到现在一共投了8份简历。分别是 阿里、腾讯、网易互娱、美团、快手、字节、though works、360。

3月12日，我收到了第一个来自腾讯的面试邀请。无法掩饰内心的激动，但是由于准备不够充分，一面挂

3月16日，360笔试后再无消息。

3月18日，收到though works未通过简历筛选通知。

3月25日，下午收到了腾讯3.26面试通知。晚上阿里蚂蚁金服临时发起面试，并在结束后立即通知了隔天二面通知。

3月26日，阿里中午二面问了很简单的一个算法思想，晚上腾讯一面开始了聊天轰炸模式（90min+手撕代码）。并且在晚上同时收到了阿里和腾讯的下一步面试通知。

3月27日，下午两点腾讯面试，二面面试官问的很简单。20分钟结束战斗，然后和面试官聊了聊天。面完结束不久阿里打来电话，问了一些项目、网络和数据库。同一天两次面试真的是太辛苦，累到不想说话。大概一小时，收到了阿里的面试通知，腾讯的本次面试通过通知。并且官网查询了一下简历状态是HR面试状态。

3月30日，阿里HR面试，简单问问家庭状况又问了绩点问题。阿里HR问题很犀利，到无法回答那种。

4月2日，腾讯HR简历状态更变成GM面试，但还是没有面试通知。

...漫长的等待...

4月8日，腾讯GM临时发起电话面试，聊了一会C++内存调试相关问题。面完GM给了口头offer。

4月9日，阿里的offer到了，让我30天之内确认接受offer。由于腾讯面试已到后期，并且阿里岗位不是很理想，所以没有立即接受。

4月13日，腾讯的HR面试通知，晚上和HR小姐姐聊了一会。小姐姐很温柔的解释了为什么GM和HR面试要等很久。

4月14日，简历状态已完成。

4月26日，腾讯offer call，晚上offer mail就到了。同时撕了阿里的offer。

4月27日，照相、复印、打印、签材料、准备银行卡。并回复offer mail。下午收到了入职指引。

4月28日，觉得春招差不多了，写一篇总结。



以上是今年春招所有的经历，期间鸽了美团、快手、网易的笔试。字节仍然没有消息。

**Comment by shijiexiao** [comment]
兄弟，腾讯哪个部门？ wxg？

**Comment by wenner987** [comment]
> 兄弟，腾讯哪个部门？ wxg？

cdg金融
